/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BlockRateMarketInterface extends Interface {
    getFunction(nameOrSignature: "getProduct" | "isSeller" | "listProduct" | "owner" | "updateStock"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProductListed" | "StockUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getProduct', values: [string]): string;
encodeFunctionData(functionFragment: 'isSeller', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'listProduct', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateStock', values: [string, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSeller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStock', data: BytesLike): Result;
  }

  
    export namespace ProductListedEvent {
      export type InputTuple = [productId: string, seller: AddressLike, price: BigNumberish, stock: BigNumberish];
      export type OutputTuple = [productId: string, seller: string, price: bigint, stock: bigint];
      export interface OutputObject {productId: string, seller: string, price: bigint, stock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StockUpdatedEvent {
      export type InputTuple = [productId: string, newStock: BigNumberish];
      export type OutputTuple = [productId: string, newStock: bigint];
      export interface OutputObject {productId: string, newStock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BlockRateMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): BlockRateMarket;
    waitForDeployment(): Promise<this>;

    interface: BlockRateMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProduct: TypedContractMethod<
      [productId: string, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, price: bigint, stock: bigint, totalSold: bigint, exists: boolean }],
      'view'
    >
    

    
    isSeller: TypedContractMethod<
      [productId: string, addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    listProduct: TypedContractMethod<
      [productId: string, price: BigNumberish, stock: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updateStock: TypedContractMethod<
      [productId: string, newStock: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [productId: string, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, price: bigint, stock: bigint, totalSold: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'isSeller'): TypedContractMethod<
      [productId: string, addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'listProduct'): TypedContractMethod<
      [productId: string, price: BigNumberish, stock: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateStock'): TypedContractMethod<
      [productId: string, newStock: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProductListed'): TypedContractEvent<ProductListedEvent.InputTuple, ProductListedEvent.OutputTuple, ProductListedEvent.OutputObject>;
getEvent(key: 'StockUpdated'): TypedContractEvent<StockUpdatedEvent.InputTuple, StockUpdatedEvent.OutputTuple, StockUpdatedEvent.OutputObject>;

    filters: {
      
      'ProductListed(string,address,uint256,uint256)': TypedContractEvent<ProductListedEvent.InputTuple, ProductListedEvent.OutputTuple, ProductListedEvent.OutputObject>;
      ProductListed: TypedContractEvent<ProductListedEvent.InputTuple, ProductListedEvent.OutputTuple, ProductListedEvent.OutputObject>;
    

      'StockUpdated(string,uint256)': TypedContractEvent<StockUpdatedEvent.InputTuple, StockUpdatedEvent.OutputTuple, StockUpdatedEvent.OutputObject>;
      StockUpdated: TypedContractEvent<StockUpdatedEvent.InputTuple, StockUpdatedEvent.OutputTuple, StockUpdatedEvent.OutputObject>;
    
    };
  }