/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReviewRegistryInterface extends Interface {
    getFunction(nameOrSignature: "backendSigner" | "getOrderByHash" | "getReviewById" | "getReviewByOrder" | "hasReviewed" | "owner" | "setBackendSigner" | "submitReview" | "totalReviews" | "totalReviewsByProduct" | "verifyReview"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BackendSignerUpdated" | "ReviewSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'backendSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrderByHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getReviewById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getReviewByOrder', values: [string]): string;
encodeFunctionData(functionFragment: 'hasReviewed', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBackendSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitReview', values: [string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'totalReviews', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalReviewsByProduct', values: [string]): string;
encodeFunctionData(functionFragment: 'verifyReview', values: [string, string, string]): string;

    decodeFunctionResult(functionFragment: 'backendSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderByHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReviewById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReviewByOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasReviewed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBackendSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitReview', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReviews', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReviewsByProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyReview', data: BytesLike): Result;
  }

  
    export namespace BackendSignerUpdatedEvent {
      export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
      export type OutputTuple = [oldSigner: string, newSigner: string];
      export interface OutputObject {oldSigner: string, newSigner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewSubmittedEvent {
      export type InputTuple = [reviewId: BigNumberish, orderId: string, reviewHash: BytesLike, productId: string, submitter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [reviewId: bigint, orderId: string, reviewHash: string, productId: string, submitter: string, timestamp: bigint];
      export interface OutputObject {reviewId: bigint, orderId: string, reviewHash: string, productId: string, submitter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReviewRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReviewRegistry;
    waitForDeployment(): Promise<this>;

    interface: ReviewRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    backendSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOrderByHash: TypedContractMethod<
      [reviewHash: BytesLike, ],
      [string],
      'view'
    >
    

    
    getReviewById: TypedContractMethod<
      [reviewId: BigNumberish, ],
      [[string, string, string, bigint] & {orderId: string, productId: string, reviewHash: string, timestamp: bigint }],
      'view'
    >
    

    
    getReviewByOrder: TypedContractMethod<
      [orderId: string, ],
      [[bigint, string, string, bigint] & {reviewId: bigint, reviewHash: string, submitter: string, timestamp: bigint }],
      'view'
    >
    

    
    hasReviewed: TypedContractMethod<
      [orderId: string, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBackendSigner: TypedContractMethod<
      [newSigner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitReview: TypedContractMethod<
      [orderId: string, productId: string, reviewHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalReviews: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalReviewsByProduct: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    verifyReview: TypedContractMethod<
      [orderId: string, reviewContent: string, userId: string, ],
      [[boolean, string] & {isValid: boolean, storedHash: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'backendSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderByHash'): TypedContractMethod<
      [reviewHash: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReviewById'): TypedContractMethod<
      [reviewId: BigNumberish, ],
      [[string, string, string, bigint] & {orderId: string, productId: string, reviewHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getReviewByOrder'): TypedContractMethod<
      [orderId: string, ],
      [[bigint, string, string, bigint] & {reviewId: bigint, reviewHash: string, submitter: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasReviewed'): TypedContractMethod<
      [orderId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBackendSigner'): TypedContractMethod<
      [newSigner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitReview'): TypedContractMethod<
      [orderId: string, productId: string, reviewHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalReviews'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReviewsByProduct'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyReview'): TypedContractMethod<
      [orderId: string, reviewContent: string, userId: string, ],
      [[boolean, string] & {isValid: boolean, storedHash: string }],
      'view'
    >;

    getEvent(key: 'BackendSignerUpdated'): TypedContractEvent<BackendSignerUpdatedEvent.InputTuple, BackendSignerUpdatedEvent.OutputTuple, BackendSignerUpdatedEvent.OutputObject>;
getEvent(key: 'ReviewSubmitted'): TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;

    filters: {
      
      'BackendSignerUpdated(address,address)': TypedContractEvent<BackendSignerUpdatedEvent.InputTuple, BackendSignerUpdatedEvent.OutputTuple, BackendSignerUpdatedEvent.OutputObject>;
      BackendSignerUpdated: TypedContractEvent<BackendSignerUpdatedEvent.InputTuple, BackendSignerUpdatedEvent.OutputTuple, BackendSignerUpdatedEvent.OutputObject>;
    

      'ReviewSubmitted(uint256,string,bytes32,string,address,uint256)': TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;
      ReviewSubmitted: TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;
    
    };
  }